// -------- legacy .contex/tile-X/ importer (Phase 12) --------
// Reads the three canonical files from a tile directory and upserts their
// content into the live database. Used when adopting existing .contex trees.
//
// Files read (all optional — missing files are silently skipped):
//   state.json    { tasks: [...], paused: boolean }
//   skills.json   { enabled: ["key", ...], disabled: [...] }
//   objective.md  full markdown
//   peers.md      auto-generated by Contex — intentionally NOT imported

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { setObjective } from './objectives.mjs';
import { setSkill } from './skills.mjs';
import { importTaskState } from './tasks.mjs';

export function importTileDir(db, { tileId, dir, workspaceId, clock } = {}) {
  const opts = { clock };
  const imported = {};

  // state.json → bulk-import tasks into the tile's channel
  try {
    const raw = readFileSync(join(dir, 'state.json'), 'utf8');
    const state = JSON.parse(raw);
    const count = importTaskState(db, { workspace_id: workspaceId, channel: tileId, state }, opts);
    imported.state = { tasks: count, paused: !!state.paused };
  } catch (_) { /* file absent or malformed — skip */ }

  // skills.json → upsert each key into skill_assignment
  try {
    const raw = readFileSync(join(dir, 'skills.json'), 'utf8');
    const skills = JSON.parse(raw);
    let enabled = 0;
    let disabled = 0;
    for (const key of (skills.enabled ?? [])) {
      setSkill(db, { tile_id: tileId, skill_key: key, enabled: true, source: 'legacy_import' }, opts);
      enabled++;
    }
    for (const key of (skills.disabled ?? [])) {
      setSkill(db, { tile_id: tileId, skill_key: key, enabled: false, source: 'legacy_import' }, opts);
      disabled++;
    }
    imported.skills = { enabled, disabled };
  } catch (_) { /* file absent or malformed — skip */ }

  // objective.md → new objective version for this tile
  try {
    const markdown = readFileSync(join(dir, 'objective.md'), 'utf8');
    setObjective(db, { tile_id: tileId, markdown, generated_by: 'legacy_import', workspace_id: workspaceId }, opts);
    imported.objective = true;
  } catch (_) { /* file absent — skip */ }

  return { tile_id: tileId, dir, imported };
}
